### ISSUE TITLE
NodeJS Installation instructions change

### ISSUE THREAD

**Issue by tejasbubane** [exercism/ecmascript#285]
A small thing I noticed in installation instructions on exercism: http://exercism.io/languages/ecmascript/installing

There are binaries available for linux as well. Hence the statement:

```
Windows and OS X users: can download an Installer
Linux users: can install it via package manager
```

Is kind-of misleading.

I would like something like:

```
There are a couple of ways to install `NodeJS`:

* via Installer Binaries: https://nodejs.org/en/download/
* via package managers: https://nodejs.org/en/download/package-manager/

Find appropriate section for your OS.
```

@matthewmorgan Please edit the content if you find anything better and mark this issue as `good first patch`.

**Comment by joelwallis** [comment]
That's a pretty good first patch!

I think that would be good to use package managers *IF* they provide a version of Node.js that's just _recent enough_. If that's not the case, just use binaries then.

**Comment by lindakatcodes** [comment]
Created a pull request for this - https://github.com/exercism/ecmascript/pull/354

Still very new to this, so if anyone has any suggestions I'm open to them!
