### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by tejasbubane** [exercism/ecmascript#287]
README has a link to `x-api`'s contributing guide with the text:

```
Please see the contributing guide
``` 

This is confusing and gives an impression about contributing to ecmascript track. The `x-api` link has nothing to do with contributing to our track.

We either:

1. Change the text to something like `For an in-depth discussion of how exercism language tracks and exercises work, please see the contributing guide` (just like [xruby](https://github.com/exercism/xruby#contributing-guide)) in which case that link makes sense.
2. Setup our own contributing guide.

**Comment by tejasbubane** [comment]
Until we discuss about our own contributing guide (if at all we decide to have one), let's settle down on changing the text to `For an in-depth discussion of how exercism language tracks and exercises work, please see the contributing guide` (just like [xruby](https://github.com/exercism/xruby#contributing-guide)). 

Marking this as `good first patch`.

**Comment by riktimmondal** [comment]
Please have a look at my first PR

**Comment by tejasbubane** [comment]
Closing via #341
