### ISSUE TITLE
Update tests and makefile to use Jest's "test" method

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/ecmascript#315]
Jest is capable of using Jasmine's `it` and `xit` methods, but has its own `test` and `xtest`.  I opened this issue to see what @exercism/ecmascripts think about switching from the Jasmine style to the Jest style for this track.  Should we bother, or leave things as they are?

**Comment by joelwallis** [comment]
If we're going to switch, it makes sense to switch everything - including the current test codebase, to Jest. I mean, if we're going to support Jest's `test`/`xtest`, we should completely rip out Jasmine from the project and stick with Jest instead.

**Comment by matthewmorgan** [comment]
@joelwallis I agree with you completely.  If we make the change, we should change it everywhere.

If no one has any objections, let's say:

Success Criteria:
- All specfiles are updated to replace `it()` with `test()`, and `xit()` with `xtest()`.
- The Makefile is updated to reflect the same change.

Any other @exercism/ecmascripts care to weigh in?

**Comment by rchavarria** [comment]
If we switched to Jest, let's go Jest.

Beside specs and `Makefile` (to replace `xtest` with `test`). I think there is some occurrence in any doc about how to run tests, so docs should be checked too.

**Comment by matthewmorgan** [comment]
Ah good point 😁

**Comment by tejasbubane** [comment]
Good point @matthewmorgan 👍  All jest docs seem to be using `test` instead of `it`. Although it they seem aliases to me, it makes sense to switch to the `jest-style`. 

Also jest seems to be moving away from jasmine in future versions (https://github.com/facebook/jest/pull/3668), although I don't think they will remove the `it` syntax in near future.
