### ISSUE TITLE
Nextercism configuration

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/ecmascript#324]
taken from @rchavarria 's related issue on the javascript track.  @exercism/ecmascripts We can do the work there first, and port it here after:

As stated in #321, Exercism will be moving to a tree-shaped track rather than a linear one, as described in the [progression & learning in Exercism](https://github.com/exercism/docs/blob/master/about/conception/progression.md) design document.

So, some tasks must be done: 

- [ ] Add a rough estimate of difficulty to each exercise (scale: 1-10) if it hasn't already one
- [ ] Add topics to exercises that has no topics yet
- [ ] Choose *at most 20 exercises* to be core exercises (set `core: true`, and delete the `unlocked_by key`)
- [ ] For each exercise that is not core, decide which exercise is the prerequisite (max 1)
- [ ] If possible, leave 3 or 4 simple exercises as (`core: false`, `unlocked_by: null`), as this will provide new participants with some exercises that they can tackle even if they have not finished the first core exercise.

**Comment by rchavarria** [comment]
I think all tasks have been done. @exercism/ecmascripts - could this issue be closed?

**Comment by tejasbubane** [comment]
Confirming that all tasks have been completed.
