### ISSUE TITLE
Port simple-linked-list exercise from JavaScript track

### ISSUE THREAD

**Issue by rchavarria** [exercism/ecmascript#333]
As part of the job to make the track compatible with *Nextercism*, we identified there are missing exercises in this track that are present in the [JavaScript](https://github.com/exercism/javascript) track. One of them is [simple-linked-list](https://github.com/exercism/javascript/tree/master/exercises/simple-linked-list).

The task would be to add the `simple-linked-list` exercise to this track, copying files from the JavaScript track and adapting the code to the ECMAScript 6 standard.

Basic steps would include:

1. Copy all files from `<javascript repo>/exercises/simple-linked-list` (https://github.com/exercism/javascript) to `<ecmascript repo>/exercises/simple-linked-list` (https://github.com/exercism/ecmascript)
2. Copy the main `package.json` file (it's in the root folder of the `ecmascript` repo https://github.com/exercism/ecmascript/blob/master/package.json) to the `<ecmascript repo>/exercises/simple-linked-list` folder
3. Adapt the code in `simple-linked-list.spec.js` file to use ECMAScript 6 features (`import` modules, arrow functions, `const` and/or `let`, any other feature you think will make the code better). Additionally, the JavaScript track uses Jasmine where the ECMAScript track uses Jest.  So, `it` and `xit` must be *translated* to `test` and `xtest`. Feel free to adapt `example.js` as well, just for fun (as long as tests pass)
4. In the `README.md` of the exercise, replace sections from *Setup* and below (Setup, Making the test suite pass, Source and Submitting incomplete solutions) with similar sections from any ECMAScript exercise, for example [`accumulate` README](https://github.com/exercism/ecmascript/blob/master/exercises/accumulate/README.md). They'll include Setup, Requirements, Making the test suite pass, Source and Submitting incomplete solutions.
5. Copy some exercise information from [JavaScript `config.json` file](https://github.com/exercism/javascript/blob/master/config.json) to the [ECMAScript `config.json` file](https://github.com/exercism/ecmascript/blob/master/config.json). This information is an object in the `exercises` array property with a `slug` property equals to `simple-linked-list`. Copy that object and place it in the same (or most similar) position in the ECMAScript `config.json` file. Both `config.json` files are in the root folder of the repo.

@exercism/ecmascripts - Do you miss something here?

**Comment by apapirovski** [comment]
I believe this can be closed now btw.

**Comment by joelwallis** [comment]
Closed by #345.

**Comment by joelwallis** [comment]
@apapirovski nice work!
