### ISSUE TITLE
Update formatting in ABOUT.md for Nextercism

### ISSUE THREAD

**Issue by rchavarria** [exercism/ecmascript#339]
Issue https://github.com/exercism/meta/issues/85 needs some checks in this track

**Comment by trvrfrd** [comment]
I can take a stab at this in the next few days if it still needs to be done.

**Comment by matthewmorgan** [comment]
@trvrfrd I believe this _does_ still need a look.  Thanks!

**Comment by matthewmorgan** [comment]
@trvrfrd are you still interested in this one?

**Comment by trvrfrd** [comment]
Hi @matthewmorgan! I have a PR open for this (#374) which I only just realize was linking to the wrong issue, so it did not show up on this one. Oops!!!

I believe the PR was still waiting for some feedback from other maintainers about what exactly the scope of the change was.

**Comment by matthewmorgan** [comment]
(smacks forehead) of course!

I think you have @rchavarria 's feedback, and a couple of 'thumbs up ' from me and @tejasbubane so I think you're one minor change away rom being ready to go.  Sorry to keep you waiting on this, I'll comment further on #374.
