### ISSUE TITLE
Document skipping of tests

### ISSUE THREAD

**Issue by tejasbubane** [exercism/ecmascript#360]
Taken from https://github.com/exercism/ruby/issues/753

We have a [doc for tests](https://github.com/exercism/ecmascript/blob/master/docs/TESTS.md) which is rendered [here](http://exercism.io/languages/ecmascript/tests) on the exercism website. 

**Task:** Mention about skipped tests in this doc. 

* Why they are skipped? 
So as to enable users to concentrate on one test at a time and enable one by one as they evolve the solution.

* How to enable them?
Change `xtest` to `test`.

All tests except the first one are skipped. You can refer any file under exercises eg. [this one](https://github.com/exercism/ecmascript/blob/master/exercises/acronym/acronym.spec.js).

**Comment by gstvribs** [comment]
i would like to work on this issue !

**Comment by tejasbubane** [comment]
@gstvribs Go for it!

**Comment by gstvribs** [comment]
Implemented by #372
