### ISSUE TITLE
Port `nucleotide-count` exercise from JavaScript track

### ISSUE THREAD

**Issue by tejasbubane** [exercism/ecmascript#361]
The task would be to add the `nucleotide-count` exercise to this track, copying files from the JavaScript track and adapting the code to the ECMAScript 6 standard.

Basic steps would include:

1. Copy all files from `<javascript repo>/exercises/nucleotide-count` (https://github.com/exercism/javascript) to `<ecmascript repo>/exercises/nucleotide-count` (https://github.com/exercism/ecmascript)
2. Copy the main `package.json` file (it's in the root folder of the `ecmascript` repo https://github.com/exercism/ecmascript/blob/master/package.json) to the `<ecmascript repo>/exercises/nucleotide-count` folder
3. Adapt the code in `nucleotide-count.spec.js` file to use ECMAScript 6 features (`import` modules, arrow functions, `const` and/or `let`, any other feature you think will make the code better). Additionally, the JavaScript track uses `Jasmine` where the ECMAScript track uses `Jest`.  So, `it` and `xit` must be *translated* to `test` and `xtest`. Feel free to adapt `example.js` as well, just for fun (as long as tests pass)
4. We have a standard set of test cases that the problem should cover in all languages on exercism in the [common problem specifications repo](https://github.com/exercism/problem-specifications/blob/master/exercises/nucleotide-count/canonical-data.json). Check if all test-cases from here are covered. If there are any cases missing or additional cases, please comment in the PR regarding them.
5. In the `README.md` of the exercise, replace sections from *Setup* and below (Setup, Making the test suite pass, Source and Submitting incomplete solutions) with similar sections from any ECMAScript exercise, for example [`accumulate` README](https://github.com/exercism/ecmascript/blob/master/exercises/accumulate/README.md). They'll include Setup, Requirements, Making the test suite pass, Source and Submitting incomplete solutions.
6. Copy some exercise information from [JavaScript `config.json` file](https://github.com/exercism/javascript/blob/master/config.json) to the [ECMAScript `config.json` file](https://github.com/exercism/ecmascript/blob/master/config.json). This information is an object in the `exercises` array property with a `slug` property equals to `nucleotide-count`. Copy that object and place it in the same (or most similar) position in the ECMAScript `config.json` file. Both `config.json` files are in the root folder of the repo.

**Comment by raphaelfp** [comment]
May I take this one?

**Comment by matthewmorgan** [comment]
@raphaelfp Please do!

The usual practice is to open a new PR with a title like

## Dibs - port exercise nulceotide-count from JavaScript track

You can start the PR with an empty commit.  If you need information on forking the repo or making an empty commit, let me know and I can help.

**Comment by matthewmorgan** [comment]
@tejasbubane @raphaelfp I just realized there is already an open PR for this exercise #349.  

@tejasbubane this was originally held up because of some changes needed to the problem-specifications repo.  Do you want to check in with the contributor @Vankog and see if he intends to finish the work?  

@Vankog's PR has been sitting idle for about six weeks now.  I would ask him, give him a day or two to respond, and if we don't hear from him we should close that PR and give @raphaelfp the go-ahead.  He's done a bunch of work, we should at least give him a chance to respond before we move on.

**Comment by tejasbubane** [comment]
> I just realized there is already an open PR for this exercise #349.

Yikes! Sorry. I totally missed that PR. I was looking to open up a few issues with relatively easy-to-implement exercises for hacktoberfest. Hence opened this issue.



> @Vankog's PR has been sitting idle for about six weeks now. I would ask him, give him a day or two to respond, and if we don't hear from him we should close that PR and give @raphaelfp the go-ahead. Vankog's done a bunch of work, we should at least give him a chance to respond before we move on.

Sound good 👍

**Comment by tejasbubane** [comment]
@raphaelfp Meanwhile you are welcome to pick up another exercise from this list: http://exercism.io/languages/ecmascript/todo

**Comment by Vankog** [comment]
The work on the canonical data is still going on. There is very much talking involved. ^^

Here is the current progress:
https://github.com/exercism/problem-specifications/pull/895#issuecomment-336448399

**Comment by matthewmorgan** [comment]
OK @Vankog thanks for the update.

**Comment by tejasbubane** [comment]
Since @Vankog is working on this, I think this issue can be closed. Sorry for the noise, my bad I did not see the already open PR.
