### ISSUE TITLE
Change installation link in exercise READMEs

### ISSUE THREAD

**Issue by tejasbubane** [exercism/ecmascript#370]
Each [exercise](https://github.com/exercism/ecmascript/tree/master/exercises) has a [README file with a setup link in it](https://github.com/exercism/ecmascript/blob/master/exercises/accumulate/README.md#setup).

The link points to http://exercism.io/languages/ecmascript/ but the setup instructions are in http://exercism.io/languages/ecmascript/installation. 

**Task:** Change the link to the correct installation link in README files of `all` exercises.

**Comment by lantran** [comment]
I would like to work on this issue.

**Comment by tejasbubane** [comment]
@lantran Go for it!

**Comment by lantran** [comment]
PR submitted.
