### ISSUE TITLE
Recommended nodejs versions

### ISSUE THREAD

**Issue by tejasbubane** [exercism/ecmascript#377]
[Nodejs 9.0 was released](https://nodejs.org/en/blog/release/v9.0.0/) yesterday and [8.9 is now LTS](https://nodejs.org/en/blog/release/v8.9.0/).

I am not sure if any discussion on this happened before, I could not find any, hence the issue.

Since we [recommend LTS version in the javascript track](http://exercism.io/languages/javascript/installation), should we recommend the latest version (9.0 as of now) in this track? And use these same recommended versions in CI?

**Comment by rchavarria** [comment]
How stable is considered v9.0? How often does it get updated? Sorry, I'm a bit lazy, and I don't want to update the recommended version every now and then. Maybe, recommending the latest LTS version is enough too in this track.

Anyway, before recommending users to use a version, we should get that version working on the track. I think there won't be any major issue. Just to be sure users won't be the first to face them.

**Comment by tejasbubane** [comment]
@rchavarria Both 9.0 and 8.9 should be pretty stable in my opinion. I think node version does not matter much especially for this track since we are using babel with env preset - which includes pretty much all latest ES features. 

That being said this was a meta issue for both tracks and my concern was mainly with the relation between recommended version and the CI. Although versions don't matter much, I feel both should be same - whatever they are - it is always better to have some convention. 

Currently javascript track recommends latest LTS but CI uses latest node version (which would be 9 - now or soon - depending upon travis support).
This track does not recommend anything. 

Hence to have one convention in the installations instructions, we can mention either:

1. LTS for javascript track and latest for ecmascript track.
2. LTS in both tracks

and use the same versions in CI.

For changing versions - you don't need to do anything on travis since `node` means latest version and `lts/*` stands for latest LTS release - and they get updated themselves.

**Comment by matthewmorgan** [comment]
We had recently discussed this on a different PR with @KamilMalek.  Unfortunately I can't find it, and I'm not sure if it was this track or the JS track.

I'd be in favor of using LTS on both tracks at this point.  I don't see anything (at this point) in Node v9 that seems relevant to the exercises, but correct me if I'm wrong.

Is linting on the JS track enough to prevent users from implementing ES6 or later style solutions on that track?  If the goal is to provide an environment that is ES5 compatible, and nudges people toward ES5-style solutions, maybe we need to be linting as part of the test process, or maybe we need to regress it to an older, ES5-only version of Node. 

My point is, I think the two tracks should _clearly_ support different sets of language features, or be merged.  Otherwise I think we risk confusing people.

**Comment by tejasbubane** [comment]
> I'd be in favor of using LTS on both tracks at this point. I don't see anything (at this point) in Node v9 that seems relevant to the exercises, but correct me if I'm wrong.

Yup, I don't think v9 makes much difference since we use Babel anyways. I just wanted to settle on some agreement on the recommended versions and use the same in CI. I would wait for a couple of days to see if others have any opinion on this - then go ahead and change the installation instructions and `travis.yml`.

**Comment by rchavarria** [comment]
> For changing versions - we don't need to do anything on travis since node means latest version and lts/* stands for latest LTS release - and they get updated themselves.

I didn't know that. So, I'm ok suggesting latest LTS in both tracks and having `lts/*` for Travis.

> Is linting on the JS track enough to prevent users from implementing ES6 or later style solutions on that track?

I think it is. In javascript track, ESLint config extends `eslint-config-airbnb-es5` (see file https://github.com/exercism/javascript/blob/master/.eslintrc.json)

About merging both tracks, it's the eternal discussion. I think we're reaching the point where we should start thinking into merging them. Or, said in a different way, how to deprecate one of the two tracks (ecmascript probably).
