### ISSUE TITLE
"unlocked_by" must not be null for non-core exercises

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/ecmascript#387]
@exercism/ecmascripts correct me if I'm wrong here, but my understanding of the new setup is that exercises should either be `core: true` or have a non-null `unlocked_by` value.

If I am right, then we have 6 exercises currently that are `core: false` and `unlocked_by: null` that we need to assign `unlocked_by` parents to.

?

I am going to enter the same issue for JavaScript.

**Comment by rchavarria** [comment]
I think the instructions said there could be some non-core exercises that don't need to be unlocked by any specific exercise. I mean, some exercises (an undefined number, just a few of them), should be marked as non-core and don't have any other exercise as dependency. This could be used to provide users some freedom when choosing a new exercise to implement.

This would be an a

**Comment by rchavarria** [comment]
I found the *original* instructions: #321 

> If possible, leave 3 or 4 simple exercises as (core: false, unlocked_by: null), as this will provide new participants with some exercises that they can tackle even if they have not finished the first core exercise.

Of course, this might be changed since this summer. But I'm not aware of that.

**Comment by matthewmorgan** [comment]
@rchavarria thanks for your feedback on this.  I'm going to close it for now.
