### ISSUE TITLE
robot-simulator: test doesn't fail

### ISSUE THREAD

**Issue by jscheffner** [exercism/ecmascript#407]
The *robot-simulator* exercise includes a test to make sure that in case of an invalid argument an error message is thrown and that this message is correct. Unfortunately, the test doesn't fail if nothing is thrown.

I already created a pull request that solves the issue but maybe it wasn't reviewed yet because I didn't create an issue.

**Comment by matthewmorgan** [comment]
@jscheffner thanks for opening the issue-- your PR hasn't been reviewed simply because I've not found the time to do it.  Thanks for your contribution, please be patient and I can get to it in the next week or so.
